### ISSUE TITLE
QA_Multipliers_Experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#9] opened 2016-04-22 04:55 UTC
Defect Description :
In the simulation page of  "Multipliers" experiment,when we click on load and import buttons and import a image , the imported image is not displaying on the screen instead the image should be displayed on the screen

Actual Result :
In the simulation page of  "Multipliers" experiment,when we click on load and import buttons and import a image , the imported image is not displaying on the screen

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/Multipliers/Multipliers_06_Experiment_p1.org

Attachment:
![9](https://cloud.githubusercontent.com/assets/14869397/14733348/f8ba1d1a-087f-11e6-802b-8f32a5015843.png)

**Comment by sadhanareddy** [comment] 2016-06-22 10:28
Both Load and import buttons are working the way it should work. When the load and import buttons are clicked, circuit is getting loaded. Load button is to load the saved circuits from your machine onto the circuit board.

But there was no proper instruction given, for how to import the circuit. Now added a point in the procedure how to import the circuit. Hence the issue is resolved now.

**Import button is to : This is an important feature that lets you construct building blocks. A circuit from your machine is imported to the mid panel, but will appear as a block or a box with input and output terminals. The name of the element is that of the imported file. The named terminals will have their saved names. The input and output nodes will come in the same order from top to bottom as created. This allows one to build on circuits saved as blocks. For instance, an full adder you design using gates can be saved as a block and used in later circuits as an adder-block.**

**Comment by sravanthimodepu** [comment] 2016-06-24 06:13
Issue is fixed now. Hence closing the issue.

**Closed by sravanthimodepu** 2016-06-24 06:13 UTC
Labels: Category: Functionality, Developed By: VLEAD, Release Number: Production, Resolved, Severity: S1
